In [53]:
import numpy as np

# ARRAY

In [54]:
ARRAY1=np.array([[1234],[56789]])

In [55]:
ARRAY1

array([[ 1234],
       [56789]])

# RANDOM

In [56]:
nump2 = np.random.randint(0,45,size=(4,5))


In [57]:
nump2

array([[40, 30, 29, 18, 27],
       [14, 44, 43, 28,  9],
       [35, 31, 17, 22, 44],
       [18, 20, 37, 25, 11]])

# ARANGE

In [58]:
nump3 = np.arange(5,25,2)

In [59]:
nump3

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# DIVIDE

In [60]:
Nump4 = np.divide(10,2)


In [63]:
Nump4

5.0